# Generated by Django 5.0.4 on 2024-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(max_length=200)),
            ],
        ),
    ]
