# Generated by Django 5.0.4 on 2024-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadTipo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('campo_adicional1', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovedadTipo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('campo_adicional2', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Novedad',
        ),
    ]
