# Generated by Django 5.0.4 on 2024-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0002_novedadtipo1_novedadtipo2_delete_novedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2024-05-01')),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='NovedadTipo1',
        ),
        migrations.DeleteModel(
            name='NovedadTipo2',
        ),
    ]
