# Generated by Django 5.0.4 on 2024-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0003_novedad_delete_novedadtipo1_delete_novedadtipo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='detalle_opcion1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='detalle_opcion2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='detalle_opcion3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo_novedad',
            field=models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], default='opcion1', max_length=50),
        ),
    ]
