# Generated by Django 5.0.4 on 2024-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0005_alter_novedad_detalle_opcion2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadTipo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2024-05-01')),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], default='opcion1', max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('detalle_opcion1', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovedadTipo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2024-05-01')),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], default='opcion1', max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('detalle_opcion2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovedadTipo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2024-05-01')),
                ('persona', models.CharField(max_length=200)),
                ('tipo_novedad', models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], default='opcion1', max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('detalle_opcion3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Novedad',
        ),
    ]
