# Generated by Django 5.0.4 on 2024-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0006_novedadtipo1_novedadtipo2_novedadtipo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadtipo1',
            name='tipo_novedad',
            field=models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], max_length=50),
        ),
        migrations.AlterField(
            model_name='novedadtipo2',
            name='tipo_novedad',
            field=models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], max_length=50),
        ),
        migrations.AlterField(
            model_name='novedadtipo3',
            name='tipo_novedad',
            field=models.CharField(choices=[('opcion1', 'Ausencias injustificadas.'), ('opcion2', 'Calamidades, permisos no remunerados/ remunerados'), ('opcion3', 'Cambios de turno')], max_length=50),
        ),
    ]
