# Generated by Django 5.0.4 on 2024-06-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0007_alter_novedadtipo1_tipo_novedad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('zona', models.CharField(max_length=200)),
                ('novedad', models.TextField()),
                ('cedula_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softwareids.usuario')),
            ],
        ),
    ]
