# Generated by Django 5.0.4 on 2024-07-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softwareids', '0008_usuario_campo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovedadTipo1',
        ),
        migrations.DeleteModel(
            name='NovedadTipo2',
        ),
        migrations.DeleteModel(
            name='NovedadTipo3',
        ),
    ]
