version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 solicitudesfua.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nombre_bd
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña

volumes:
  postgres_data:
