name: Build and deploy static web app to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd IDS_SOFTWARE_BETA/solicitudesfua
          npm install
          npm run build

      - name: Deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/IDS_SOFTWARE_BETA/solicitudesfua"
          api_location: "" # Si tienes una API, especifica su ubicación aquí
          output_location: "build" # Ajusta esta ubicación si es necesario
