name: Build and deploy Python app to Azure Web App - app-softwareids-prod-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      

      - name: Zip artifact for deployment
        run: |
          docker save ids_software_beta | gzip > ids_software_beta.tar.gz

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ids_software_beta.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'app-softwareids-prod-001'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SOFTWAREIDS }}
